name: Lead Time Automation Build

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo ${{ secrets.BKB_INFRA_DOCKER_PASSWORD }} | docker login -u bkbinfra  --password-stdin
      - name: Build Image
        run: |
          docker build -t bkbinfra/release_kpi_extractor .
          docker push bkbinfra/release_kpi_extractor
