name: Lead Time For Release
on:
  release:
    types: [published]

  workflow_dispatch: # To allow manual launch with specified version
    inputs:
      version:
        description: "Version for which to extract the KPIs"

permissions:
  contents: write
  pull-requests: read

jobs:
  extractLeadTime:
    runs-on: ubuntu-latest

    steps:
      - name: Bind KPIs Notes to Release
        run: |
          docker pull bkbinfra/release_kpi_extractor
          if ["${{ github.event.inputs.version }}" != ""]; then
            docker run --rm -e GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN}} bkbinfra/release_kpi_extractor -d true -v "${{ github.event.inputs.version }}" -r "${{ github.repository}}"
          else
            docker run --rm -e GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN}} -v $GITHUB_EVENT_PATH:/usr/app/event.json bkbinfra/release_kpi_extractor -d true
          fi
