name: Lead Time For Release
on:
  release:
    types: [published]

  workflow_dispatch: # To allow manual launch with specified version
    inputs:
      version:
        required: true
        description: "Version for which to extract the KPIs"

permissions:
  contents: write
  pull-requests: read

jobs:
  extractLeadTime:
    runs-on: ubuntu-latest

    steps:
      - name: Bind KPIs Notes to Release
        run: |
          if [ "$VERSION" != "" ]; then
            docker run --rm -e PROJECT_NAME=KpiExtractor -e GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN}} bkbinfra/release_kpi_extractor -d true -v $VERSION -r $REPOSITORY
          else
            docker run --rm -e PROJECT_NAME=KpiExtractor -e GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN}} -v $GITHUB_EVENT_PATH:/usr/app/event.json bkbinfra/release_kpi_extractor -d true
          fi
        env:
          REPOSITORY: ${{ github.repository }}
          VERSION: ${{ github.event.inputs.version }}
